name: Scheduled Builds

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  api:
    name: Request Build on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/itopaloglu83/itopaloglu83.github.io/pages/builds"
